sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alfredocm80/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alfredocm80/react-test npm test -- --coverage

after_success:
  - docker build -t alfredocm80/multi-client ./client
  - docker build -t alfredocm80/multi-nginx ./nginx
  - docker build -t alfredocm80/multi-server ./server
  - docker build -t alfredocm80/multi-worker ./worker
#Proceso de login a docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Cargar imagenes a docker hub
  - docker push alfredocm80/multi-client
  - docker push alfredocm80/multi-nginx
  - docker push alfredocm80/multi-server
  - docker push alfredocm80/multi-worker