version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

services:
  - docker

init:
  - docker build -t alfredocm80/react-test -f ./client/Dockerfile.dev ./client
  - docker run alfredocm80/react-test npm test -- --coverage
  - docker build -t alfredocm80/multi-client ./client
  - docker build -t alfredocm80/multi-nginx ./nginx
  - docker build -t alfredocm80/multi-server ./server
  - docker build -t alfredocm80/multi-worker ./worker
#Proceso de login a docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Cargar imagenes a docker hub
  - docker push alfredocm80/multi-client
  - docker push alfredocm80/multi-nginx
  - docker push alfredocm80/multi-server
  - docker push alfredocm80/multi-worker
    
